services:
  mikrotik-backup:
    image: ghcr.io/yoganovvaindra/mikrotik-backup:v1.2
    container_name: mikrotik-backup
    network_mode: bridge
    restart: always
    environment:
      - MIKROTIK_ROUTER=${MIKROTIK_ROUTER}
      - MIKROTIK_USER=${MIKROTIK_USER}
      - MIKROTIK_BACKUP_ENCRYPT=${MIKROTIK_BACKUP_ENCRYPT}
      - MIKROTIK_SSH_PORT=${MIKROTIK_SSH_PORT}
      - MIKROTIK_MAX_BACKUPS=${MIKROTIK_MAX_BACKUPS}
      - TZDATA=${TZDATA}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - ./backups:/home/backupuser/backups
      - ./id_rsa:/home/backupuser/.ssh/id_rsa:ro
      - ./id_rsa.pub:/home/backupuser/.ssh/id_rsa.pub:ro
      - ./known_hosts:/home/backupuser/.ssh/known_hosts:rw