services:
  mikrotik-backup:
    image: ghcr.io/yoganovvaindra/mikrotik-backup:v1
    container_name: mikrotik-backup
    network_mode: bridge
    restart: always
    environment:
      - MIKROTIK_ROUTER=10.1.1.127
      - MIKROTIK_USER=admin
      - MIKROTIK_BACKUP_ENCRYPT=password
      - MIKROTIK_MAX_BACKUPS=3
      - TZDATA=Asia/Jakarta
      - CRON_SCHEDULE=0 0 * * *
    volumes:
      - ./backups:/home/backupuser/backups
      - ./id_rsa:/home/backupuser/.ssh/id_rsa:ro
      - ./known_hosts:/home/backupuser/.ssh/known_hosts:rw